### ISSUE TITLE
The BYR currency is incorrect, it should be BYN

### ISSUE THREAD

**Issue by krzyzewski** [ash-jc-allen/laravel-exchange-rates#155]
The BYR currency is incorrect, it should be BYN

**Comment by ash-jc-allen** [comment]
Hey @krzyzewski, please could you point to where this is invalid so I can try and get a fix in place for it? 🙂

**Comment by krzyzewski** [comment]
![image](https://github.com/ash-jc-allen/laravel-exchange-rates/assets/17343499/04af4002-787c-476b-8c25-1487d2327599)

**Comment by ash-jc-allen** [comment]
Ahh nice one, thanks!
 
I've just had a look at the docs for the APIs the package supports and it looks like there's a mixture of support for BYN and BYR. I've not tested the APIs though to check whether both currencies are supported.

So I think it's worth leaving the BYR in there for anyone who's working with historical currency conversions. But I'll get BYN added to the list later this week so people can start using it 😄

**Comment by ash-jc-allen** [comment]
Hey @krzyzewski, I've just released v7.5.0 that adds "BYN" as a valid currency symbol 😄 

https://github.com/ash-jc-allen/laravel-exchange-rates/releases/tag/v7.5.0

**Comment by krzyzewski** [comment]
Thank you very much, another currency has appeared: https://en.wikipedia.org/wiki/Venezuelan_bol%C3%ADvar
