### ISSUE TITLE
Currency VES

### ISSUE THREAD

**Issue by krzyzewski** [ash-jc-allen/laravel-exchange-rates#160]
Hi. Another currency has appeared: https://en.wikipedia.org/wiki/Venezuelan_bol%C3%ADvar (code "VES")
Similar to https://github.com/ash-jc-allen/laravel-exchange-rates/issues/155

**Comment by ash-jc-allen** [comment]
Hey! I'd be more than happy to accept a PR to add this currency 🙂

**Comment by ash-jc-allen** [comment]
Yeah, support for BYN was added as part of the v7.5.0 release. If you make a PR to add support for VES, I'll release it as part of v7.6.0 🙂

**Comment by krzyzewski** [comment]
Ok, i updated composer with v7.5.0
