### ISSUE TITLE
Support for Laravel 7

### ISSUE THREAD

**Issue by theonly27** [ash-jc-allen/laravel-exchange-rates#27]

**Comment by ash-jc-allen** [comment]
Hi @theonly27, I'm intending on adding support for it at the weekend. If you need it before then, I'd be happy to accept a pull request if you want to add it yourself? :smile:

**Comment by ash-jc-allen** [comment]
Support for Laravel 7 is now included in the latest release (v2.1.0).

https://github.com/ash-jc-allen/laravel-exchange-rates/releases/tag/v2.1.0
