### ISSUE TITLE
memory usage when installing

### ISSUE THREAD

**Issue by ayophanz** [ash-jc-allen/laravel-exchange-rates#30]
Fatal error: Allowed memory size of 1610612736 bytes exhausted (tried to allocate 4096 bytes)
https://prnt.sc/snge38

**Comment by ash-jc-allen** [comment]
Hi @ayophanz, have you had any luck with following the steps in the error message to increase your memory? https://getcomposer.org/doc/articles/troubleshooting.md#memory-limit-errors

If you still have this problem, do you still have this problem when trying to install the package in a new Laravel project?

**Comment by ayophanz** [comment]
I fixed the problem by changing the memory_limit, but more than 1gb is
being used when installing the package and this is not new project.

**Comment by ash-jc-allen** [comment]
Sweet, I'm glad you managed to get it sorted. How do you know that more than 1GB is being used? If you've got a way of determining it, I'll look into it and see if there's something I can do to sort it :smile:

**Comment by ayophanz** [comment]
first I try 1gb memory_limit and try to install but still error happens
then I decide to 2gb and it works.

**Comment by ash-jc-allen** [comment]
Ahh okay, so you determined it through trial-and-error. From having a quick browse online, it looks like it's not a problem with the package itself. It seems like Composer can be a bit greedy with memory sometimes.

I've not had this reported by anyone else using this package. I've been using it in a few projects as well and not encountered this issue myself either. But, I'll keep an eye out to see if this happens again with anybody else; I hope the package comes in handy! :smile:
