### ISSUE TITLE
Do not cache

### ISSUE THREAD

**Issue by ash-jc-allen** [ash-jc-allen/laravel-exchange-rates#35]
At the moment, we force all exchange rates that are fetched to be stored in the cache before we return them. This could be an optional feature.

This feature could be added as either an optional parameter for each of the methods that it affects, or it could be added as a new chained method (e.g. - ``` ...->doNotCache()->... ```).

**Comment by ash-jc-allen** [comment]
#38

**Comment by ash-jc-allen** [comment]
This feature was added in release [v3.0.0](https://github.com/ash-jc-allen/laravel-exchange-rates/releases/tag/v3.0.0).

**Comment by olimortimer** [comment]
How long does the cache last for, please?

**Comment by ash-jc-allen** [comment]
Hey @olimortimer! The exchange rates are cached forever without an expiry date/time 🙂
