### ISSUE TITLE
Installation Failed (Guzzle version Issue)

### ISSUE THREAD

**Issue by Devscaleupally** [ash-jc-allen/laravel-exchange-rates#44]
While installing the package, in my local as well as over the server I am facing this issue of Guzzle.

After firing this `composer require ashallendesign/laravel-exchange-rates`
Below is the output I am getting.

I have tried to change the Guzzle package too but it was not help full
`Problem 1
    - Installation request for ashallendesign/laravel-exchange-rates ^3.0 -> satisfiable by ashallendesign/laravel-exchange-rates[v3.0.0].
    - Conclusion: remove guzzlehttp/guzzle 7.0.1
    - Conclusion: don't install guzzlehttp/guzzle 7.0.1
    - ashallendesign/laravel-exchange-rates v3.0.0 requires guzzlehttp/guzzle ^6.3 -> satisfiable by guzzlehttp/guzzle[6.3.0, 6.3.1, 6.3.2, 6.3.3, 6.4.0, 6.4.1, 6.5.0, 6.5.1, 6.5.2, 
6.5.3, 6.5.4, 6.5.5, 6.5.x-dev].
    - Can only install one of: guzzlehttp/guzzle[6.3.0, 7.0.1].
    - Can only install one of: guzzlehttp/guzzle[6.3.1, 7.0.1].
    - Can only install one of: guzzlehttp/guzzle[6.3.2, 7.0.1].
    - Can only install one of: guzzlehttp/guzzle[6.3.3, 7.0.1].
    - Can only install one of: guzzlehttp/guzzle[6.4.0, 7.0.1].
    - Can only install one of: guzzlehttp/guzzle[6.4.1, 7.0.1].
    - Can only install one of: guzzlehttp/guzzle[6.5.0, 7.0.1].
    - Can only install one of: guzzlehttp/guzzle[6.5.1, 7.0.1].
    - Can only install one of: guzzlehttp/guzzle[6.5.2, 7.0.1].
    - Can only install one of: guzzlehttp/guzzle[6.5.3, 7.0.1].
    - Can only install one of: guzzlehttp/guzzle[6.5.4, 7.0.1].
    - Can only install one of: guzzlehttp/guzzle[6.5.5, 7.0.1].
    - Can only install one of: guzzlehttp/guzzle[6.5.x-dev, 7.0.1].
    - Installation request for guzzlehttp/guzzle (locked at 7.0.1) -> satisfiable by guzzlehttp/guzzle[7.0.1].`

This is the screenshot - https://prnt.sc/u6mqh1

**Comment by ash-jc-allen** [comment]
Hi @Devscaleupally, sorry to hear that you're having problems with the package.

At the moment, this package doesn't support Guzzle 7, so you'll more than likely have to use Guzzle 6 to be able to use it. I should be adding Guzzle 7 support in due time, but if you'd like to make a PR to speed up the process, I'd be happy for you to make one :smile:

**Comment by ash-jc-allen** [comment]
Just a quick update on this one for you @Devscaleupally.

As for Laravel Exchange Rates v3.2.0, there is now support for Guzzle 7 (https://github.com/ash-jc-allen/laravel-exchange-rates/releases/tag/v3.2.0).
