### ISSUE TITLE
Invalid conversion for Float values

### ISSUE THREAD

**Issue by zpoll92** [ash-jc-allen/laravel-exchange-rates#48]
When I'm trying to convert (using the Convert method) float values e.g.: '0.99' or '2.99' it converts the number to Integer and therefore returns an invalid value. For example, it returns 0 if you want to convert '0.99'.

**Comment by ash-jc-allen** [comment]
Hi @zpoll92, sorry to hear that you're having problems.

The ` convert() ` method accepts integers for monetary value. You'll need to pass it in in your currencies lowest denomination. For example, to convert $0.99 you'd need to pass in 99 and to convert $2.99 you'd need to pass in 299.

There's an example in the docs if this helps:
https://github.com/ash-jc-allen/laravel-exchange-rates#convert-currencies

I hope you manage to get it working 😃
