### ISSUE TITLE
How to add Local Currency

### ISSUE THREAD

**Issue by sarfarazsavvy** [ash-jc-allen/laravel-exchange-rates#51]
Hi 

I want to add this package to one of my project but I can able to add Pkr as currency. Pkr is Pakistani currency.

Regards

**Comment by ash-jc-allen** [comment]
Hi @sarfarazsavvy!

Unfortunately, it looks like the PKR isn't supplied as a currency by the exchangeratesapi API. If it gets added to the API, I'll make sure that it gets added to the package as a new currency :smile: 

Sorry that I can't help much on this at the moment.

Thanks!
