### ISSUE TITLE
Can't convert decimal numbers

### ISSUE THREAD

**Issue by hugo411** [ash-jc-allen/laravel-exchange-rates#54]
Hi, all my conversions are working well except when converting for example 0.25USD to CAD, it will result 0.

**Comment by ash-jc-allen** [comment]
The ` convert() ` method accepts integers for monetary value. You'll need to pass it in in your currency's lowest denomination. For example, to convert 0.25USD you'd need to pass in 25, and to convert $2.99 you'd need to pass in 299.

There's an example in the docs if this helps:
https://github.com/ash-jc-allen/laravel-exchange-rates#convert-currencies

I hope you manage to get it working 😃
