### ISSUE TITLE
base_currency_access_restricted

### ISSUE THREAD

**Issue by premmurugesan** [ash-jc-allen/laravel-exchange-rates#58]
For a free plan, `exchangeRate()` function working for base currency EUR, Not working for other currencies, When attempting to set other currencies as the base currency issue occurring `base_currency_access_restricted`
<img width="663" alt="Screenshot 2021-04-05 at 10 57 26 AM" src="https://user-images.githubusercontent.com/65813053/113540406-b7ed9f80-95fd-11eb-84e7-f66da3769475.png">

**Comment by ash-jc-allen** [comment]
Hi @premmurugesan, sorry that you're having issues with the package. Unfortunately, as of a few days ago, the API has completely changed and some of the features are now behind a paywall.

So, from what I can see, without paying for access to the API, you now can't use a base currency in the requests anymore.
