### ISSUE TITLE
You have not specified a Time-Frame

### ISSUE THREAD

**Issue by riaanlom** [ash-jc-allen/laravel-exchange-rates#62]
exchangeRateBetweenDateRange does not conform to their API. 

makeRequestForExchangeRates should be updated to start_date and end_date

`$result = $this->requestBuilder->makeRequest('/timeseries', [
            'base'     => $from,
            'start_at' => $date->format('Y-m-d'),
            'end_at'   => $endDate->format('Y-m-d'),
            'symbols'  => $symbols,
        ]);
`

**Comment by ash-jc-allen** [comment]
Hi @riaanlom, it looks like you're probably right with this one. It must have been something that got missed off when switching over to the new version of the API recently. If you'd like to make a PR for this, I'd be happy to take a look at it :smile:

**Comment by riaanlom** [comment]
Cool created a PR

**Comment by ash-jc-allen** [comment]
Perfect! Thanks for that, I'll take a look at it later today and hopefully get it pulled in.

I do apologise for this by the way, the recent updates to the package were very rushed after the API got updated suddenly.

**Comment by ash-jc-allen** [comment]
Thanks again for the PR on this one @riaanlom. The changes have been merged and are included in a v4.0.1 release that I've just put up (https://github.com/ash-jc-allen/laravel-exchange-rates/releases/tag/v4.0.1).
