### ISSUE TITLE
Update $allowableCurrencies

### ISSUE THREAD

**Issue by martyn-v** [ash-jc-allen/laravel-exchange-rates#65]
With the paid subscription, exchangeratesapi.io seems to have increased the number of currencies it's support. Would it be possible to update the $allowableCurrencies array to reflect this or make it configurable?

https://exchangeratesapi.io/currencies/

**Comment by ash-jc-allen** [comment]
Thanks for letting me know about this, I wasn't aware that new currencies had been added. I'll take a look at the PR later today and hopefully get it pulled :smile:

**Comment by martyn-v** [comment]
> Thanks for letting me know about this, I wasn't aware that new currencies had been added. I'll take a look at the PR later today and hopefully get it pulled 😄

Happy to, I accidentally stumbled across it as well but seems they've added tons more currencies. Let me know if there is anything you need me to change and I'd be happy to do it. I ran the tests and they all ran fine but I dont think this impacted much there.
