### ISSUE TITLE
How do you generate Facade php docs?

### ISSUE THREAD

**Issue by ardzz** [ash-jc-allen/laravel-exchange-rates#67]

**Comment by ash-jc-allen** [comment]
Hi @ardzz, I manually added the docblocks for the methods in the facade. There is probably some type of automated tool that can be used to generate them though :)

**Comment by ardzz** [comment]
I made my own tool to mass generate PHPDocs for facade laravel, check this out
https://gist.github.com/ardzz/473f8b994714370b917d6232ce5146f0
